# These are supported funding model platforms

github: kirklin # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: kirklin # Replace with a single Patreon username
custom: ["https://www.buymeacoffee.com/linkirk"]
