import type { Theme } from "@unocss/preset-mini";

export const generateDefaultVariables = (selectorName: string, theme: Theme) => {
  return {
    "--un-chinese-typography-root-selector": `.${selectorName}`,
    "--un-chinese-typography-font-stack-sans": theme?.fontFamily?.sans,
    "--un-chinese-typography-font-stack-serif": theme?.fontFamily?.serif,
    "--un-chinese-typography-font-stack-mono": theme?.fontFamily?.mono,
    "--un-chinese-typography-font-stack-symbol": theme?.fontFamily?.symbol,
    "--un-chinese-typography-font-family-hei": theme?.fontFamily?.hei,
    "--un-chinese-typography-font-family-song": theme?.fontFamily?.song,
    "--un-chinese-typography-font-family-kai": theme?.fontFamily?.kai,
    "--un-chinese-typography-font-family-hei-black": "var(--un-chinese-typography-font-family-hei), font-black",
    "--un-chinese-typography-font-family-song-black": "var(--un-chinese-typography-font-family-song), font-black",
    "--un-chinese-typography-font-family-kai-black": "var(--un-chinese-typography-font-family-kai), font-black",
    "--un-chinese-typography-font-family-mono": "var(--un-chinese-typography-font-stack-mono), monospace, var(--un-chinese-typography-font-stack-symbol)",
    "--un-chinese-typography-font-weight-bolder": "800",
    "--un-chinese-typography-font-weight-bold": "600",
    "--un-chinese-typography-font-weight-normal": "400",
    "--un-chinese-typography-font-weight-lighter": "200",
    "--un-chinese-typography-font-size-normal": "16px",
    "--un-chinese-typography-font-size-x-large": "20px",
    "--un-chinese-typography-font-size-large": "18px",
    "--un-chinese-typography-font-size-small": "14px",
    "--un-chinese-typography-font-size-x-small": "12px",
    "--un-chinese-typography-font-size-h1": "32px",
    "--un-chinese-typography-font-size-h2": "24px",
    "--un-chinese-typography-font-size-h3": "20px",
    "--un-chinese-typography-font-size-h4": "18px",
    "--un-chinese-typography-font-size-h5": "16px",
    "--un-chinese-typography-font-size-h6": "14px",
    "--un-chinese-typography-line-length": "42em",
    "--un-chinese-typography-line-height-normal": "1.5",
    "--un-chinese-typography-letter-spacing-normal": "0",
    "--un-chinese-typography-letter-spacing-small": "0.01em",
    "--un-chinese-typography-letter-spacing-medium": "0.02em",
    "--un-chinese-typography-letter-spacing-large": "0.05em",
    "--un-chinese-typography-line-height-size-normal": "calc(var(--un-chinese-typography-font-size-normal) * var(--un-chinese-typography-line-height-normal))",
    "--un-chinese-typography-line-height-size-large": "var(--un-chinese-typography-line-height-size-normal)",
    "--un-chinese-typography-line-height-size-x-large": "calc(var(--un-chinese-typography-font-size-x-large) * var(--un-chinese-typography-line-height-normal))",
    "--un-chinese-typography-line-height-size-small": "var(--un-chinese-typography-line-height-size-normal)",
    "--un-chinese-typography-line-height-size-x-small": "18px",
    "--un-chinese-typography-line-height-size-h1": "48px",
    "--un-chinese-typography-line-height-size-h2": "36px",
    "--un-chinese-typography-line-height-size-h3": "36px",
    "--un-chinese-typography-line-height-size-h4": "24px",
    "--un-chinese-typography-line-height-size-h5": "24px",
    "--un-chinese-typography-line-height-size-h6": "24px",
    "--un-chinese-typography-std-block-unit": "var(--un-chinese-typography-line-height-size-normal)",
    "--un-chinese-typography-std-inline-unit": "var(--un-chinese-typography-font-size-normal)",
    "--un-chinese-typography-text-indent-length": "2em",
    "--un-chinese-typography-text-indent-size": "calc(var(--un-chinese-typography-font-size-normal) * 2)",
    // 中文引号 Chinese Quote Set
    // `cn`：中华人民共和国国家标准——GB/T 15834-2011《标点符号用法》 http://www.moe.gov.cn/ewebeditor/uploadfile/2015/01/13/20150113091548267.pdf
    // `tw`：中国台湾地区标准——《重訂標點符號手冊》 https://language.moe.gov.tw/001/Upload/FILES/SITE_CONTENT/M0001/HAU/h6.htm
    // `common`：部分中文社区（如知乎）在简体中文里亦采用与中国台湾地区标准一致的规范。
    "--un-chinese-typography-chinese-quote-presets-cn-horizontal": "\"“\" \"”\" \"‘\" \"’\"",
    "--un-chinese-typography-chinese-quote-presets-cn-vertical": "\"『\" \"』\" \"「\" \"」\"",
    "--un-chinese-typography-chinese-quote-presets-tw-horizontal": "\"「\" \"」\" \"『\" \"』\"",
    "--un-chinese-typography-chinese-quote-presets-tw-vertical": "\"「\" \"」\" \"『\" \"』\"",
    "--un-chinese-typography-chinese-quote-presets-common-horizontal": "\"「\" \"」\" \"『\" \"』\"",
    "--un-chinese-typography-chinese-quote-presets-common-vertical": "\"「\" \"」\" \"『\" \"』\"",
    "--un-chinese-typography-chinese-quote-set": "common",
  };
};
